# permissions for end users to edit nsqclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nsqcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nsq-operator
    app.kubernetes.io/part-of: nsq-operator
    app.kubernetes.io/managed-by: kustomize
  name: nsqcluster-editor-role
rules:
- apiGroups:
  - apps.yebaoping.cn
  resources:
  - nsqclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.yebaoping.cn
  resources:
  - nsqclusters/status
  verbs:
  - get
