//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 yebaoping.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NsqAdminStatus) DeepCopyInto(out *NsqAdminStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NsqAdminStatus.
func (in *NsqAdminStatus) DeepCopy() *NsqAdminStatus {
	if in == nil {
		return nil
	}
	out := new(NsqAdminStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NsqAdminTemplate) DeepCopyInto(out *NsqAdminTemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NsqAdminTemplate.
func (in *NsqAdminTemplate) DeepCopy() *NsqAdminTemplate {
	if in == nil {
		return nil
	}
	out := new(NsqAdminTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NsqCluster) DeepCopyInto(out *NsqCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NsqCluster.
func (in *NsqCluster) DeepCopy() *NsqCluster {
	if in == nil {
		return nil
	}
	out := new(NsqCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NsqCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NsqClusterList) DeepCopyInto(out *NsqClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NsqCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NsqClusterList.
func (in *NsqClusterList) DeepCopy() *NsqClusterList {
	if in == nil {
		return nil
	}
	out := new(NsqClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NsqClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NsqClusterSpec) DeepCopyInto(out *NsqClusterSpec) {
	*out = *in
	out.NsqLookupD = in.NsqLookupD
	out.NsqD = in.NsqD
	out.NsqAdmin = in.NsqAdmin
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NsqClusterSpec.
func (in *NsqClusterSpec) DeepCopy() *NsqClusterSpec {
	if in == nil {
		return nil
	}
	out := new(NsqClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NsqClusterStatus) DeepCopyInto(out *NsqClusterStatus) {
	*out = *in
	in.NsqLookupD.DeepCopyInto(&out.NsqLookupD)
	in.NsqD.DeepCopyInto(&out.NsqD)
	out.NsqAdmin = in.NsqAdmin
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NsqClusterStatus.
func (in *NsqClusterStatus) DeepCopy() *NsqClusterStatus {
	if in == nil {
		return nil
	}
	out := new(NsqClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NsqDStatus) DeepCopyInto(out *NsqDStatus) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NsqDStatus.
func (in *NsqDStatus) DeepCopy() *NsqDStatus {
	if in == nil {
		return nil
	}
	out := new(NsqDStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NsqDTemplate) DeepCopyInto(out *NsqDTemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NsqDTemplate.
func (in *NsqDTemplate) DeepCopy() *NsqDTemplate {
	if in == nil {
		return nil
	}
	out := new(NsqDTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NsqLookupDStatus) DeepCopyInto(out *NsqLookupDStatus) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NsqLookupDStatus.
func (in *NsqLookupDStatus) DeepCopy() *NsqLookupDStatus {
	if in == nil {
		return nil
	}
	out := new(NsqLookupDStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NsqLookupDTemplate) DeepCopyInto(out *NsqLookupDTemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NsqLookupDTemplate.
func (in *NsqLookupDTemplate) DeepCopy() *NsqLookupDTemplate {
	if in == nil {
		return nil
	}
	out := new(NsqLookupDTemplate)
	in.DeepCopyInto(out)
	return out
}
